#spring:
#  datasource:  
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://10.112.30.17:3306/lineplatform?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=TRUE
#      username: lineapp
#      password: 123456
